### ISSUE TITLE
ImportError: cannot import name 'deprecated' from 'typing_extensions

### ISSUE THREAD

**Issue by johnroyer** [jyhsu2000/CKIPService#2]
步驟：
- [下載 models](https://github.com/ckiplab/ckiptagger#1-download-model-files) 到 `data/` 目錄
- 清空 docker container & docker images
- `docker-compose up`

錯誤訊息：
```
ckip-service | Traceback (most recent call last):
ckip-service |   File "./ckip_service.py", line 6, in <module>
ckip-service |     from fastapi import FastAPI
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/fastapi/__init__.py", line 7, in <module>
ckip-service |     from .applications import FastAPI as FastAPI
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 16, in <module>
ckip-service |     from fastapi import routing
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 22, in <module>
ckip-service |     from fastapi import params
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/fastapi/params.py", line 5, in <module>
ckip-service |     from fastapi.openapi.models import Example
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/fastapi/openapi/models.py", line 4, in <module>
ckip-service |     from fastapi._compat import (
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/fastapi/_compat.py", line 20, in <module>
ckip-service |     from fastapi.exceptions import RequestErrorModel
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/fastapi/exceptions.py", line 3, in <module>
ckip-service |     from pydantic import BaseModel, create_model
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/pydantic/__init__.py", line 13, in <module>
ckip-service |     from . import dataclasses
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/pydantic/dataclasses.py", line 11, in <module>
ckip-service |     from ._internal import _config, _decorators, _typing_extra
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/pydantic/_internal/_config.py", line 9, in <module>
ckip-service |     from ..config import ConfigDict, ExtraValues, JsonEncoder, JsonSchemaExtraCallable
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/pydantic/config.py", line 9, in <module>
ckip-service |     from .deprecated.config import BaseConfig
ckip-service |   File "/usr/local/lib/python3.8/dist-packages/pydantic/deprecated/config.py", line 6, in <module>
ckip-service |     from typing_extensions import Literal, deprecated
ckip-service | ImportError: cannot import name 'deprecated' from 'typing_extensions' (/usr/local/lib/python3.8/dist-packages/typing_extensions.py)
```

docker container 中的 Python 為 `v3.8.10`：
```sh
docker run jyhsu2000/ckip-service  python --version
Python 3.8.10
```

請問是否為操作有問題？或是 build 失敗？

謝謝

**Comment by jyhsu2000** [comment]
似乎是 Python 版本、Pydantic、typing_extensions 之間的問題🤔

目前先透過更換基礎 Docker Image 解決
升級至 `tensorflow/tensorflow:2.14.0`，對應 Python 3.11
```diff
- FROM tensorflow/tensorflow:2.9.1
+ FROM tensorflow/tensorflow:2.14.0
```
